### ISSUE TITLE
RuntimeError: Invalid magic number; corrupt file?

### ISSUE THREAD

**Issue by yjyyy** [vasgaowei/pytorch_MELM#1]
when i load the vgg16.pth, why it reminds me that it is a corrupt file?

**Comment by harrywang725** [comment]
I guess you should down the file again.Maybe you didn't down the file successfully

**Comment by vasgaowei** [comment]
yeah, i met the same issue before when i ran the code, and just like @harrywang725 said, downloading the right vgg16.pth file will work.

**Comment by yjyyy** [comment]
yes, the vgg16.pth file in  https://drive.google.com/drive/folders/0B1_fAEgxdnvJSmF3YUlZcHFqWTQ may be corrupted, please download the right file in https://drive.google.com/drive/folders/1FV6ZOHOxLMQjE4ujTNOObI7lN8USH0v_?usp=sharing
