### ISSUE TITLE
Reproducibility results

### ISSUE THREAD

**Issue by zwyyy215** [vasgaowei/pytorch_MELM#6]
Hello, thank you for your hard work. I would like to ask.What is the mAP of your experimental results?Is it the same as the result in the paper?

**Comment by vasgaowei** [comment]
My experiment's performance mAP is 47.98, trained in PASCAL_VOC 2007 trainval and tested on PASCAL_VOC test . The mAP is a little better than the papers' 47.3.

**Comment by vasgaowei** [comment]
And the backbone network is vgg16

**Comment by zwyyy215** [comment]
好的，谢谢。想问问您，MELM的作者又出了一篇文章，C-MIL：Continuation Multiple Instance Learning for Weakly Supervised Object Detection这篇论文。因为这篇文章与MELM的作者是同一个人，但是这两篇文章的开源代码都是lua。我想问问，您还会整理CMIL的pytorch版本吗？
