### ISSUE TITLE
Did you use the ‘gt_bbox’ annotation in your model?

### ISSUE THREAD

**Issue by magemoumou** [vasgaowei/pytorch_MELM#8]
I looked all through your code.
Then I found that during the generation of the 'roidb', you used the 'gt_bbox' annotation saved in the file: pytorch_MELM/data/VOCdevkit2007/VOC2007/Annotations.
But the original model tends be a "Weakly Supervised Detection Model" which just using the image label annotation without the 'gt_bbox' I believe.

**Comment by vasgaowei** [comment]
No, I don't use the "gt_box". You can check my code carefully. I don't change the 'roidb' generation code, but during the forward propagation, I don't use the 'gt_box'.

**Comment by magemoumou** [comment]
OK, I finally run through your code.
Maybe I am supposed to transform my dataset to pascal voc format or not change your code.
Thanks.
